package com.example.transit_ags

object Constants {
    const val DATABASE_NAME = "TransITA"
    const val DATABASE_VERSION = 10
    const val TABLE_PARADA = "Parada"
    const val TABLE_CONDUCTOR = "Conductor"
    const val TABLE_PUNTOS_RECARGA = "Puntos_Recarga"
    const val TABLE_RUTA = "Ruta"
    const val TABLE_STATUS = "Status"
    const val TABLE_TIPO_TRANSPORTE = "Tipo_Transporte"
    const val TABLE_TIPO_PERSONA = "Tipo_Persona"
    const val TABLE_COSTO = "Costo"
    const val TABLE_TIEMPO = "Tiempo"
    const val TABLE_ESTADO_TAXI = "Estado_Taxi"
    const val TABLE_TARJETAS = "Tarjetas"
    const val TABLE_PARADEROS = "Paraderos"
    const val TABLE_SOS = "SOS"
    const val TABLE_USUARIO = "Usuario"
    const val TABLE_TIPO_RESPUESTA = "Tipo_Respuesta"
    const val TABLE_TIPO_REPORTE = "Tipo_Reporte"
    const val TABLE_PREGUNTA_REPORTE = "Pregunta_Reporte"
    const val TABLE_REPORTE = "Reporte"
    const val TABLE_RESPUESTA_REPORTE = "Respuesta_Reporte"
    const val TABLE_USUARIO_RESPUESTA_REPORTE = "Usuario_Respuestas_Reporte"
    const val TABLE_AUTOBUS = "Autobus"
    const val TABLE_COMBI = "Combi"
    const val TABLE_TAXI = "Taxi"
    const val TABLE_UBICACION_BUS = "Ubicacion_Bus"
    const val TABLE_UBICACION_COMBI = "Ubicacion_Combi"
    const val TABLE_UBICACION_TAXI = "Ubicacion_Taxi"
    const val TABLE_RUTA_HAS_PARADA = "Ruta_has_Parada"
    const val TABLE_TIEMPO_PROMEDIO = "Tiempo_Promedio"

}